# vowl · Basic Tutorial

The main walkthrough of the **vowl** library for validating data against [ODCS](https://github.com/bitol-io/open-data-contract-standard) data contracts. Run it top-to-bottom.

This notebook covers the everyday workflow: setup, running a validation, and understanding the results. Five further folders build on it:

- `2_multiple_sources/`: validating one contract across multiple sources
- `3_real_databases/`: server-side validation with Testcontainers (needs Docker)
- `4_advanced_usage/`: explicit adapters (incl. `PooledAdapter`) and row filtering
- `5_results/`: a tour of every result shape (annotated tables, residues, saved files)
- `6_dq_metrics/`: the run's DQ metrics as `dq_metrics.json` and OpenTelemetry, plus a local OTel stack

## Contents

1. [Setup](#1-setup)
2. [Auto-Mapped Validation](#2-auto-mapped-validation): Pandas, Polars, other inputs
3. [The ValidationResult Object](#3-validationresult)
4. [Annotated Output and Saved Files](#4-annotated-output)

Generated CSV/JSON artifacts are written to this notebook's local `outputs/` folder.

<a id="1-setup"></a>
## 1. Setup

Install the dependencies (skipped during execution), then resolve the dataset paths used throughout the notebook.

In [1]:
# Install vowl (skipped during execution)
# %pip install 'vowl[all]'

In [2]:
from pathlib import Path

# Walk up to the repo root (works no matter how deep this notebook sits)
REPO_ROOT = Path.cwd()
while not (REPO_ROOT / "tests" / "hdb_resale").exists() and REPO_ROOT != REPO_ROOT.parent:
    REPO_ROOT = REPO_ROOT.parent

# Single-source: HDB Resale dataset
HDB_DIR = REPO_ROOT / "tests" / "hdb_resale"
HDB_CSV = HDB_DIR / "HDBResaleWithErrors.csv"
HDB_CONTRACT = HDB_DIR / "hdb_resale_simple.yaml"  # Switch to "hdb_resale.yaml" for a more complex contract

# Multi-source: Employee dataset (payroll + employee list)
EMPLOYEE_DIR = REPO_ROOT / "tests" / "employee"
EMPLOYEE_PAYROLL_CSV = EMPLOYEE_DIR / "demo_employee_payroll.csv"
EMPLOYEE_LIST_CSV = EMPLOYEE_DIR / "demo_employee_list.csv"
EMPLOYEE_CONTRACT = EMPLOYEE_DIR / "employee_payroll_datacontract.yaml"

# Common imports used throughout this notebook
import pandas as pd
from vowl import validate_data

# --- Quieten known, benign warnings emitted by this demo ---
import warnings

# vowl surfaces UserWarnings (Arrow type coercion, multi-schema adapter reuse)
# that are informational for this demo dataset.
warnings.filterwarnings("ignore", category=UserWarning,
                        module=r"vowl\.validation\.runner")

In [3]:
# Confirm every dataset path resolves
print(f"HDB CSV exists:          {HDB_CSV.exists()}")
print(f"HDB contract exists:     {HDB_CONTRACT.exists()}")
print(f"Employee payroll CSV exists:  {EMPLOYEE_PAYROLL_CSV.exists()}")
print(f"Employee list CSV exists: {EMPLOYEE_LIST_CSV.exists()}")
print(f"Employee contract exists:     {EMPLOYEE_CONTRACT.exists()}")

HDB CSV exists:          True
HDB contract exists:     True
Employee payroll CSV exists:  True
Employee list CSV exists: True
Employee contract exists:     True

---

# Running a Validation

The simplest way to feed your data into vowl is to hand it a DataFrame and let it auto-detect the input type. For explicit adapters and row filtering, see the [Advanced Usage notebook](../4_advanced_usage/advanced_usage.ipynb).

<a id="2-auto-mapped-validation"></a>
## 2. Auto-Mapped Validation

When you pass a DataFrame directly to `validate_data(df=...)`, vowl uses a `DataSourceMapper` to automatically detect the input type (pandas, Polars, PyArrow, cuDF, Modin, etc.) and route it to the appropriate adapter -- in most cases, an in-memory DuckDB connection via `IbisAdapter`.

This is the simplest way to validate data. For explicit control over the adapter, see the [Advanced Usage notebook](../4_advanced_usage/advanced_usage.ipynb).

### 2.1 Pandas

In [4]:
import pandas as pd
from vowl import validate_data

df = pd.read_csv(HDB_CSV, low_memory=False).fillna("")

In [5]:
# Inspect the loaded data
print(f"Loaded {len(df)} rows, {len(df.columns)} columns")
df.head()

Loaded 201879 rows, 11 columns

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2017-01,ANG MO KIO,2 ROOM,406,ANG MO KIO AVE 10,10 TO 12,44.0,Improved,1979,61 years 04 months,232000.0
1,2017-01,ANG MO KIO,3 ROOM,108,ANG MO KIO AVE 4,01 TO 03,67.0,New Generation,1978,60 years 07 months,250000.0
2,2017-01,ANG MO KIO,3 ROOM,602,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,262000.0
3,2017-01,ANG MO KIO,3 ROOM,465,ANG MO KIO AVE 10,04 TO 06,68.0,New Generation,1980,62 years 01 month,265000.0
4,2017-01,ANG MO KIO,3 ROOM,601,ANG MO KIO AVE 5,01 TO 03,67.0,New Generation,1980,62 years 05 months,265000.0

In [6]:
result = validate_data(contract=str(HDB_CONTRACT), df=df)

In [7]:
# Show the full validation report
result.display_full_report()

=== Data Quality Validation Results ===
   Contract Version:      v3.2.0
   Contract ID:           c11443ee-542f-4442-b28d-2d224342be37
   Schemas:               hdb_resale_prices

 OVERALL DATA QUALITY
   Overall:
     Checks Pass Rate:       7 / 9 (77.7%)

   hdb_resale_prices:
     Overall:
       Checks Pass Rate:       7 / 9 (77.7%)
       ERRORED Checks:         0
       Passed Rows:            201,865 / 201,879 (99.9%)
     Single Table:
       Checks Pass Rate:       7 / 9 (77.7%)
       ERRORED Checks:         0
     Multi Table:
       Checks Pass Rate:       0 / 0 (N/A)
       ERRORED Checks:         0
       Non-unique Failed Rows: 0


 CHECK RESULTS
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| check_id                           | Target                           | tables_in_query   | status | operator | expected | actual | execution time |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| Month                              | hdb_resale_prices.month          | hdb_resale_prices | FAILED | mustBe   | 0        | 2      | 22.95 ms       |
| floor_area_must_be_less_than_200   | hdb_resale_prices.floor_area_sqm | hdb_resale_prices | FAILED | mustBe   | 0        | 12     | 19.25 ms       |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| flat_type_column_exists_check      | hdb_resale_prices.flat_type      | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 8.03 ms        |
| flat_type_enum_check               | hdb_resale_prices.flat_type      | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 7.89 ms        |
| floor_area_sqm_column_exists_check | hdb_resale_prices.floor_area_sqm | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 7.87 ms        |
| month_column_exists_check          | hdb_resale_prices.month          | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 7.87 ms        |
| month_logical_type_check           | hdb_resale_prices.month          | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 9.46 ms        |
| resale_price_column_exists_check   | hdb_resale_prices.resale_price   | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 5.17 ms        |
| resale_price_must_not_exceed_2m    | hdb_resale_prices.resale_price   | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 18.95 ms       |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
Total Execution:       107.44 ms

=== Failed Checks and Rows (up to 5 row(s) per failed check) ===

  hdb_resale_prices
    Single checks

      [Month]
        Operator:   mustBe
        Expected:   0
        Actual:     2
        Target:   hdb_resale_prices.month
        Details:  Based on ISO 8601 | YYYY-MM
        Rule:     SELECT COUNT(*) FROM "hdb_resale_prices" WHERE NOT REGEXP_MATCHES(TRY_CAST(month AS TEXT), '^[0-9]{4}-(0[1-9]|1[0-2])$')
        Rows shown: 2 of 2
+----------+--------+-----------+-------+--------------+--------------+----------------+---------------+---------------------+--------------------+--------------+
| month    | town   | flat_type | block | street_name  | storey_range | floor_area_sqm | flat_model    | lease_commence_date | remaining_lease    | resale_price |
+----------+--------+-----------+-------+--------------+--------------+----------------+---------------+---------------------+--------------------+--------------+
| 2017-jan | BEDOK  | 5 ROOM    | 21    | CHAI CHEE RD | 07 TO 09     | 130.0          | Adjoined flat | 1972                | 54 years 06 months | 530000.0     |
| 2017-jan | BISHAN | 3 ROOM    | 105   | BISHAN ST 12 | 04 TO 06     | 4.0            | Simplified    | 1985                | 67 years 11 months | 395000.0     |
+----------+--------+-----------+-------+--------------+--------------+----------------+---------------+---------------------+--------------------+--------------+

      [floor_area_must_be_less_than_200]
        Operator:   mustBe
        Expected:   0
        Actual:     12
        Target:   hdb_resale_prices.floor_area_sqm
        Details:  Check failed: expected mustBe 0, got 12
        Rule:     SELECT COUNT(*) FROM "hdb_resale_prices" WHERE TRY_CAST(floor_area_sqm AS BIGINT) >= 200
        Rows shown: 5 of 12
+---------+-----------------+-----------+-------+---------------------+--------------+----------------+--------------------+---------------------+--------------------+--------------+
| month   | town            | flat_type | block | street_name         | storey_range | floor_area_sqm | flat_model         | lease_commence_date | remaining_lease    | resale_price |
+---------+-----------------+-----------+-------+---------------------+--------------+----------------+--------------------+---------------------+--------------------+--------------+
| 2017-06 | KALLANG/WHAMPOA | 3 ROOM    | 38    | JLN BAHAGIA         | 01 TO 03     | 215.0          | Terrace            | 1972                | 54 years 01 month  | 830000.0     |
| 2017-09 | CHOA CHU KANG   | EXECUTIVE | 641   | CHOA CHU KANG ST 64 | 16 TO 18     | 215.0          | Premium Maisonette | 1998                | 79 years 04 months | 888000.0     |
| 2017-12 | KALLANG/WHAMPOA | 3 ROOM    | 65    | JLN MA'MOR          | 01 TO 03     | 249.0          | Terrace            | 1972                | 53 years 07 months | 1053888.0    |
| 2018-01 | CHOA CHU KANG   | EXECUTIVE | 639   | CHOA CHU KANG ST 64 | 10 TO 12     | 215.0          | Premium Maisonette | 1998                | 79 years           | 900000.0     |
| 2018-09 | KALLANG/WHAMPOA | 3 ROOM    | 41    | JLN BAHAGIA         | 01 TO 03     | 237.0          | Terrace            | 1972                | 52 years 10 months | 1185000.0    |
+---------+-----------------+-----------+-------+---------------------+--------------+----------------+--------------------+---------------------+--------------------+--------------+

ValidationResult(passed=False, checks=9, passed_checks=7, failed_checks=2)

<a id="22-polars"></a>
### 2.2 Polars

vowl works with any [Narwhals-compatible](https://github.com/narwhals-dev/narwhals) DataFrame. Here we use Polars with the same contract.

In [8]:
import polars as pl

polars_df = pl.read_csv(HDB_CSV, infer_schema_length=9999999) # To allow mixed type data to be detected in this demo example
result = validate_data(contract=str(HDB_CONTRACT), df=polars_df)

In [9]:
print(f"Loaded {len(polars_df)} rows via Polars")
result.display_full_report()

Loaded 201879 rows via Polars


=== Data Quality Validation Results ===
   Contract Version:      v3.2.0
   Contract ID:           c11443ee-542f-4442-b28d-2d224342be37
   Schemas:               hdb_resale_prices

 OVERALL DATA QUALITY
   Overall:
     Checks Pass Rate:       7 / 9 (77.7%)

   hdb_resale_prices:
     Overall:
       Checks Pass Rate:       7 / 9 (77.7%)
       ERRORED Checks:         0
       Passed Rows:            201,865 / 201,879 (99.9%)
     Single Table:
       Checks Pass Rate:       7 / 9 (77.7%)
       ERRORED Checks:         0
     Multi Table:
       Checks Pass Rate:       0 / 0 (N/A)
       ERRORED Checks:         0
       Non-unique Failed Rows: 0


 CHECK RESULTS
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| check_id                           | Target                           | tables_in_query   | status | operator | expected | actual | execution time |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| Month                              | hdb_resale_prices.month          | hdb_resale_prices | FAILED | mustBe   | 0        | 2      | 20.41 ms       |
| floor_area_must_be_less_than_200   | hdb_resale_prices.floor_area_sqm | hdb_resale_prices | FAILED | mustBe   | 0        | 12     | 16.16 ms       |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| flat_type_column_exists_check      | hdb_resale_prices.flat_type      | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 5.12 ms        |
| flat_type_enum_check               | hdb_resale_prices.flat_type      | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 9.32 ms        |
| floor_area_sqm_column_exists_check | hdb_resale_prices.floor_area_sqm | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 5.09 ms        |
| month_column_exists_check          | hdb_resale_prices.month          | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 4.97 ms        |
| month_logical_type_check           | hdb_resale_prices.month          | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 11.10 ms       |
| resale_price_column_exists_check   | hdb_resale_prices.resale_price   | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 7.43 ms        |
| resale_price_must_not_exceed_2m    | hdb_resale_prices.resale_price   | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 23.81 ms       |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
Total Execution:       103.42 ms

=== Failed Checks and Rows (up to 5 row(s) per failed check) ===

  hdb_resale_prices
    Single checks

      [Month]
        Operator:   mustBe
        Expected:   0
        Actual:     2
        Target:   hdb_resale_prices.month
        Details:  Based on ISO 8601 | YYYY-MM
        Rule:     SELECT COUNT(*) FROM "hdb_resale_prices" WHERE NOT REGEXP_MATCHES(TRY_CAST(month AS TEXT), '^[0-9]{4}-(0[1-9]|1[0-2])$')
        Rows shown: 2 of 2
+----------+--------+-----------+-------+--------------+--------------+----------------+---------------+---------------------+--------------------+--------------+
| month    | town   | flat_type | block | street_name  | storey_range | floor_area_sqm | flat_model    | lease_commence_date | remaining_lease    | resale_price |
+----------+--------+-----------+-------+--------------+--------------+----------------+---------------+---------------------+--------------------+--------------+
| 2017-jan | BEDOK  | 5 ROOM    | 21    | CHAI CHEE RD | 07 TO 09     | 130.0          | Adjoined flat | 1972                | 54 years 06 months | 530000.0     |
| 2017-jan | BISHAN | 3 ROOM    | 105   | BISHAN ST 12 | 04 TO 06     | 4.0            | Simplified    | 1985                | 67 years 11 months | 395000.0     |
+----------+--------+-----------+-------+--------------+--------------+----------------+---------------+---------------------+--------------------+--------------+

      [floor_area_must_be_less_than_200]
        Operator:   mustBe
        Expected:   0
        Actual:     12
        Target:   hdb_resale_prices.floor_area_sqm
        Details:  Check failed: expected mustBe 0, got 12
        Rule:     SELECT COUNT(*) FROM "hdb_resale_prices" WHERE TRY_CAST(floor_area_sqm AS BIGINT) >= 200
        Rows shown: 5 of 12
+---------+-----------------+-----------+-------+---------------------+--------------+----------------+--------------------+---------------------+--------------------+--------------+
| month   | town            | flat_type | block | street_name         | storey_range | floor_area_sqm | flat_model         | lease_commence_date | remaining_lease    | resale_price |
+---------+-----------------+-----------+-------+---------------------+--------------+----------------+--------------------+---------------------+--------------------+--------------+
| 2017-06 | KALLANG/WHAMPOA | 3 ROOM    | 38    | JLN BAHAGIA         | 01 TO 03     | 215.0          | Terrace            | 1972                | 54 years 01 month  | 830000.0     |
| 2017-09 | CHOA CHU KANG   | EXECUTIVE | 641   | CHOA CHU KANG ST 64 | 16 TO 18     | 215.0          | Premium Maisonette | 1998                | 79 years 04 months | 888000.0     |
| 2017-12 | KALLANG/WHAMPOA | 3 ROOM    | 65    | JLN MA'MOR          | 01 TO 03     | 249.0          | Terrace            | 1972                | 53 years 07 months | 1053888.0    |
| 2018-01 | CHOA CHU KANG   | EXECUTIVE | 639   | CHOA CHU KANG ST 64 | 10 TO 12     | 215.0          | Premium Maisonette | 1998                | 79 years           | 900000.0     |
| 2018-09 | KALLANG/WHAMPOA | 3 ROOM    | 41    | JLN BAHAGIA         | 01 TO 03     | 237.0          | Terrace            | 1972                | 52 years 10 months | 1185000.0    |
+---------+-----------------+-----------+-------+---------------------+--------------+----------------+--------------------+---------------------+--------------------+--------------+

ValidationResult(passed=False, checks=9, passed_checks=7, failed_checks=2)

#### Do Pandas and Polars Always Agree?

Here both report the same **2 failed checks** (7/9 pass), because none of this contract's checks look at the columns where the two libraries treat missing values differently.

They can disagree once a check touches those columns. Switch `HDB_CONTRACT` to `hdb_resale.yaml` and the `AddressBlockHouseNumber` and `Year` checks show it:

| Check | Pandas | Polars | Reason |
|-------|--------|--------|--------|
| **AddressBlockHouseNumber** | FAILED (1 row) | PASSED | Pandas `fillna("")` converts a null `block` to an empty string `""`, which fails the regex `^[A-Za-z0-9]{1,10}$`. Polars keeps it as `null`, and SQL `WHERE ... !~ pattern` evaluates to `NULL` (not `TRUE`), so the row is not counted. |
| **Year** | FAILED (3 rows) | FAILED (2 rows) | One record has an empty `lease_commence_date`. In Pandas, `fillna("")` turns it into `""` which fails the `^[0-9]{4}$` regex. In Polars, the value stays `null` and is skipped by the WHERE clause. |

This is a documented aspect of null handling across backends. See [Known Issues: Null Handling](../../docs/known-issues.md#null-handling-varies-across-backends). If you need to catch nulls explicitly, add a `nullValues` library check to your contract.

### 2.3 Other Inputs (Connection Strings, Ibis Backends, Spark, Arrow)

The auto-mapper accepts more than DataFrames. vowl detects the type and creates the appropriate `IbisAdapter` automatically.

In [10]:
# The auto-mapper supports more than just DataFrames.
# Below are other input types that validate_data() can auto-detect:

# --- Connection string (any URI that Ibis recognises) ---
# result = validate_data(contract=str(HDB_CONTRACT), df="postgresql://<user>:<password>@<host>:<port>/<dbname>")
# result = validate_data(contract=str(HDB_CONTRACT), df="snowflake://<user>:<password>@<account>/<db>/<schema>")

# --- Ibis backend (already connected) ---
# con = ibis.duckdb.connect("my_database.ddb")
# result = validate_data(contract=str(HDB_CONTRACT), df=con)

# --- PySpark DataFrame ---
# spark_df = spark.read.table("my_table")
# result = validate_data(contract=str(HDB_CONTRACT), df=spark_df)

# --- PyArrow Table ---
# import pyarrow.csv as pcsv
# arrow_table = pcsv.read_csv("data.csv")
# result = validate_data(contract=str(HDB_CONTRACT), df=arrow_table)

---

# Understanding the Results

Every `validate_data(...)` call returns a `ValidationResult`. This section covers the accessors it exposes -- summary DataFrames, failed-row views, and the annotated full table.

<a id="3-validationresult"></a>
## 3. The ValidationResult Object

The `ValidationResult` object provides several ways to inspect and export results. First, run a validation to work with.

In [11]:
# Run a validation to work with
result = validate_data(contract=str(HDB_CONTRACT), df=pd.read_csv(HDB_CSV, low_memory=False).fillna(""))

In [12]:
# Check overall pass/fail, then print the summary (without failed rows)
print(f"All checks passed: {result.passed}")
result.print_summary()

All checks passed: False


=== Data Quality Validation Results ===
   Contract Version:      v3.2.0
   Contract ID:           c11443ee-542f-4442-b28d-2d224342be37
   Schemas:               hdb_resale_prices

 OVERALL DATA QUALITY
   Overall:
     Checks Pass Rate:       7 / 9 (77.7%)

   hdb_resale_prices:
     Overall:
       Checks Pass Rate:       7 / 9 (77.7%)
       ERRORED Checks:         0
       Passed Rows:            201,865 / 201,879 (99.9%)
     Single Table:
       Checks Pass Rate:       7 / 9 (77.7%)
       ERRORED Checks:         0
     Multi Table:
       Checks Pass Rate:       0 / 0 (N/A)
       ERRORED Checks:         0
       Non-unique Failed Rows: 0


 CHECK RESULTS
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| check_id                           | Target                           | tables_in_query   | status | operator | expected | actual | execution time |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| Month                              | hdb_resale_prices.month          | hdb_resale_prices | FAILED | mustBe   | 0        | 2      | 20.40 ms       |
| floor_area_must_be_less_than_200   | hdb_resale_prices.floor_area_sqm | hdb_resale_prices | FAILED | mustBe   | 0        | 12     | 16.57 ms       |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
| flat_type_column_exists_check      | hdb_resale_prices.flat_type      | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 5.35 ms        |
| flat_type_enum_check               | hdb_resale_prices.flat_type      | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 7.20 ms        |
| floor_area_sqm_column_exists_check | hdb_resale_prices.floor_area_sqm | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 4.84 ms        |
| month_column_exists_check          | hdb_resale_prices.month          | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 5.73 ms        |
| month_logical_type_check           | hdb_resale_prices.month          | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 11.00 ms       |
| resale_price_column_exists_check   | hdb_resale_prices.resale_price   | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 4.63 ms        |
| resale_price_must_not_exceed_2m    | hdb_resale_prices.resale_price   | hdb_resale_prices | PASSED | mustBe   | 0        | 0      | 16.24 ms       |
+------------------------------------+----------------------------------+-------------------+--------+----------+----------+--------+----------------+
Total Execution:       91.95 ms

ValidationResult(passed=False, checks=9, passed_checks=7, failed_checks=2)

### Check Results DataFrame

`get_check_results_df()` returns a single DataFrame with one row per check: status, expected/actual values, execution time, dimension, and more.

In [13]:
# Full check results as a DataFrame (one row per check)
check_results_df = result.get_check_results_df()

# To include contract and check definitions in the DataFrame, use:
# check_results_df = result.get_check_results_df(include_contract_definition=True, include_check_definition=True)

In [14]:
# View the check results
check_results_df.to_pandas()

,check_name,target,schema_name,engine,dimension,status,operator,actual_value,expected_value,failed_rows_count,aggregation_type,message,rendered_implementation,tables_in_query,check_path,check_ref_type,logical_type,is_generated,execution_time_ms
0,month_column_exists_check,hdb_resale_prices.month,hdb_resale_prices,sql,conformity,PASSED,mustBe,0,0,0,count,,"SELECT COUNT(*) FROM (SELECT ""month"" FROM ""hdb...",['hdb_resale_prices'],$.schema[0].properties[0].name,DeclaredColumnExistsCheckReference,string,True,5.727209
1,month_logical_type_check,hdb_resale_prices.month,hdb_resale_prices,sql,conformity,PASSED,mustBe,0,0,0,count,,"SELECT COUNT(*) FROM ""hdb_resale_prices"" WHERE...",['hdb_resale_prices'],$.schema[0].properties[0].logicalType,LogicalTypeCheckReference,string,True,10.995333
2,flat_type_column_exists_check,hdb_resale_prices.flat_type,hdb_resale_prices,sql,conformity,PASSED,mustBe,0,0,0,count,,"SELECT COUNT(*) FROM (SELECT ""flat_type"" FROM ...",['hdb_resale_prices'],$.schema[0].properties[1].name,DeclaredColumnExistsCheckReference,NaN,True,5.351833
3,flat_type_enum_check,hdb_resale_prices.flat_type,hdb_resale_prices,sql,conformity,PASSED,mustBe,0,0,0,count,,"SELECT COUNT(*) FROM ""hdb_resale_prices"" WHERE...",['hdb_resale_prices'],$.schema[0].properties[1].enum,EnumCheckReference,NaN,True,7.197708
4,floor_area_sqm_column_exists_check,hdb_resale_prices.floor_area_sqm,hdb_resale_prices,sql,conformity,PASSED,mustBe,0,0,0,count,,"SELECT COUNT(*) FROM (SELECT ""floor_area_sqm"" ...",['hdb_resale_prices'],$.schema[0].properties[2].name,DeclaredColumnExistsCheckReference,NaN,True,4.839041
5,resale_price_column_exists_check,hdb_resale_prices.resale_price,hdb_resale_prices,sql,conformity,PASSED,mustBe,0,0,0,count,,"SELECT COUNT(*) FROM (SELECT ""resale_price"" FR...",['hdb_resale_prices'],$.schema[0].properties[3].name,DeclaredColumnExistsCheckReference,NaN,True,4.626750
6,Month,hdb_resale_prices.month,hdb_resale_prices,sql,conformity,FAILED,mustBe,2,0,2,count,,"SELECT COUNT(*) FROM ""hdb_resale_prices"" WHERE...",['hdb_resale_prices'],$.schema[0].properties[0].quality[0],SQLColumnCheckReference,string,False,20.403625
7,floor_area_must_be_less_than_200,hdb_resale_prices.floor_area_sqm,hdb_resale_prices,sql,consistency,FAILED,mustBe,12,0,12,count,,"SELECT COUNT(*) FROM ""hdb_resale_prices"" WHERE...",['hdb_resale_prices'],$.schema[0].properties[2].quality[0],SQLColumnCheckReference,NaN,False,16.570375
8,resale_price_must_not_exceed_2m,hdb_resale_prices.resale_price,hdb_resale_prices,sql,consistency,PASSED,mustBe,0,0,0,count,,"SELECT COUNT(*) FROM ""hdb_resale_prices"" WHERE...",['hdb_resale_prices'],$.schema[0].properties[3].quality[0],SQLColumnCheckReference,NaN,False,16.235958

### Failed Rows (per check)

`get_output_dfs()` returns a dict of `{check_id: DataFrame}`, one entry per failed check, containing the actual rows that failed.

In [15]:
# Failed rows grouped by check. Each key is "schema::check_name"
output_dfs = result.get_output_dfs()

In [16]:
# Display the failed rows for each check
for check_id, failed_df in output_dfs.items():
    if len(failed_df) == 0:
        continue  # Skip checks with no failed rows
    print(f"\n{'='*60}")
    print(f"Check: {check_id}  ({len(failed_df)} failed rows)")
    print(f"{'='*60}")
    display(failed_df.to_pandas().head())

============================================================
Check: hdb_resale_prices::Month  (2 failed rows)
============================================================

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,check_id,tables_in_query
0,2017-jan,BEDOK,5 ROOM,21,CHAI CHEE RD,07 TO 09,130.0,Adjoined flat,1972,54 years 06 months,530000.0,Month,hdb_resale_prices
1,2017-jan,BISHAN,3 ROOM,105,BISHAN ST 12,04 TO 06,4.0,Simplified,1985,67 years 11 months,395000.0,Month,hdb_resale_prices

============================================================
Check: hdb_resale_prices::floor_area_must_be_less_than_200  (12 failed rows)
============================================================

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price,check_id,tables_in_query
0,2017-06,KALLANG/WHAMPOA,3 ROOM,38,JLN BAHAGIA,01 TO 03,215.0,Terrace,1972,54 years 01 month,830000.0,floor_area_must_be_less_than_200,hdb_resale_prices
1,2017-09,CHOA CHU KANG,EXECUTIVE,641,CHOA CHU KANG ST 64,16 TO 18,215.0,Premium Maisonette,1998,79 years 04 months,888000.0,floor_area_must_be_less_than_200,hdb_resale_prices
2,2017-12,KALLANG/WHAMPOA,3 ROOM,65,JLN MA'MOR,01 TO 03,249.0,Terrace,1972,53 years 07 months,1053888.0,floor_area_must_be_less_than_200,hdb_resale_prices
3,2018-01,CHOA CHU KANG,EXECUTIVE,639,CHOA CHU KANG ST 64,10 TO 12,215.0,Premium Maisonette,1998,79 years,900000.0,floor_area_must_be_less_than_200,hdb_resale_prices
4,2018-09,KALLANG/WHAMPOA,3 ROOM,41,JLN BAHAGIA,01 TO 03,237.0,Terrace,1972,52 years 10 months,1185000.0,floor_area_must_be_less_than_200,hdb_resale_prices

### Saving to Disk

`result.save(...)` writes the results (CSVs, a JSON summary and the [DQ metrics](../../docs/dq-metrics/json-export.md)) to a directory.

In [17]:
# Save results to disk (CSV + JSON summary)
result.save(output_dir="outputs", prefix="vowl_demo_HDB_results")

Results saved:
   - outputs/vowl_demo_HDB_results_check_results.csv
   - outputs/vowl_demo_HDB_results_hdb_resale_prices_annotated.csv
   - outputs/vowl_demo_HDB_results_summary.json
   - outputs/vowl_demo_HDB_results_dq_metrics.json

ValidationResult(passed=False, checks=9, passed_checks=7, failed_checks=2)

<a id="4-annotated-output"></a>
## 4. Annotated Output and Saved Files

Section 3 showed the core `ValidationResult` accessors and a default `save()`. vowl can also return your **full table with a `check_info` column** (`get_annotated_output()`), hand back **residual rows** for checks that span more than one table, and save those annotated tables and residues to disk. Every run is also summed up as **DQ metrics**, which you can save as `dq_metrics.json` or export to **OpenTelemetry** as metrics, traces, and logs.

Each has its own walkthrough:

- **→ [`5_results/results_tour.ipynb`](../5_results/results_tour.ipynb)**: annotated tables, residues, and saved files
- **→ [`6_dq_metrics/dq_metrics.ipynb`](../6_dq_metrics/dq_metrics.ipynb)**: DQ metrics as JSON and OpenTelemetry

Both use this same HDB contract, so everything you learned here carries straight over.